### ISSUE TITLE
EnTK and NAMD integration for simple MDFF

### ISSUE THREAD

**Issue by daipayans** [radical-collaboration/MDFF-EnTK#4] opened 2019-09-04 14:51 UTC
@lee212 Thanks, for the EnTK protocol (https://github.com/radical-collaboration/MDFF-Error/blob/master/namd.py). Prior to submitting this job in bridges, I have the following questions:

Q1. Do I use the same details (from the OpenMM example) for the MongoDB and Rabbitmq server's url? 

Q2. Please help me understand line 39 of the script. For the simulation part we are performing simple mdff. However, looks like the analysis stage in the pipeline uses 'msm', is this correct? 
Note: The 'msm' stage is not applicable here, instead we could calculate the cross-correlation between the structure and EM density.

Thanks, 
Daipayan

**Comment by lee212** [comment] 2019-09-05 15:52
Hi Daipayan, 

Please see my answers below:

Q1. Yes, we do keep using the same environment, no changes on mongodb and rabbitMQ.

Q2. It's a label to the stage, I re-used the openmm template but with `namd` executable for the demonstration purpose. I can put a correct name to avoid confusions but thank you for pointing out that with the explanation. I agree we need to have better description in the EnTK script. I will update the `namd.py` file.

**Comment by daipayans** [comment] 2019-09-06 05:10
@lee212 Thanks. We can use the following command by sourcing VMD (command line version):
mdff check -ccc -map 4ake-target_autopsf.dx -res 5

This command will plot the CCC between each MDFF trajectory frame and the target map.

**Comment by daipayans** [comment] 2019-09-11 07:28
Hi @lee212 : Did you get a chance to implement the command shared earlier in thread to calculate the ccc for the analysis stage in the revised EnTK protocol for integration with namd? Please let me know if you have any questions. Thank you.

**Comment by lee212** [comment] 2019-09-12 19:57
Hi @daipayans , 

My test run for Simple MDFF is written here: https://github.com/radical-collaboration/MDFF-Error/blob/master/simple_mdff.py

You can find [the mdff command](https://github.com/radical-collaboration/MDFF-Error/blob/master/simple_mdff.py#L206) that you were referring at the very last stage, as it was described in 'Calculating the cross-correlation coefficient' from the example.

Simple explanation would be I write `.tcl` script in every stage where VMD is required to run. This allows me skipping interactive Tcl shell but executing same commands as a batch, like a  command line tool.

In addition, I had to use VMD 1.9.4a37 due to the missing `voltool` in the earlier version according to this, https://www.ks.uiuc.edu/Research/vmd/mailing_list/vmd-l/30532.html.

In addition, I installed and ran Situs package during the manual test but did not include in the EnTK script. Instead, I used the prepared data as suggested.

**Comment by daipayans** [comment] 2019-11-13 16:20
Hi @lee212, As I mentioned to you we don't see any NAMD trajectory files (filetype *.dcd) after executing the entk-namd protocol for MDFF with the minor modifications to the simple_mdff python script (i.e.  loading modules for individual tasks).

**Comment by benjha** [comment] 2019-11-26 01:11
> Hi @daipayans ,
> 
> My test run for Simple MDFF is written here: https://github.com/radical-collaboration/MDFF-Error/blob/master/simple_mdff.py
> 
> You can find [the mdff command](https://github.com/radical-collaboration/MDFF-Error/blob/master/simple_mdff.py#L206) that you were referring at the very last stage, as it was described in 'Calculating the cross-correlation coefficient' from the example.
> 
> Simple explanation would be I write `.tcl` script in every stage where VMD is required to run. This allows me skipping interactive Tcl shell but executing same commands as a batch, like a command line tool.
> 
> In addition, I had to use VMD 1.9.4a37 due to the missing `voltool` in the earlier version according to this, https://www.ks.uiuc.edu/Research/vmd/mailing_list/vmd-l/30532.html.

The simple MDFF example used here is based on 2009 version, thus voltool and VMD 1.9.4  is not needed, see

https://github.com/radical-collaboration/MDFF-Error/issues/7

for more details.

> 
> In addition, I installed and ran Situs package during the manual test but did not include in the EnTK script. Instead, I used the prepared data as suggested.

**Comment by lee212** [comment] 2020-04-01 17:04
@daipayans , this can be closed as we confirmed it is working on bridges, can you confirm?

**Comment by lee212** [comment] 2020-04-08 15:59
@daipayans , I will close this, for now, feel free to re-open anytime if necessary.

**Closed as completed by lee212** 2020-04-08 15:59 UTC
